#!/bin/sh
read request
while /bin/true;
do
read header
[ "$header" == $'\r' ] && break;
done

GET="${request#GET }"
HEADER="${GET% HTTP/*}"
url=`echo $HEADER | sed 's/\///'`

usage() {
echo "<h1> Welcome to the Zookeeeper! </h1>

The zookeeper is an http api to send Bluetooth Low Energy beacons to compatible
plush toys. 

<h2> Usage </h2>

Set your URL to a valid bird. Here is a list of the birds I'm aware of:
"
for BIRD in `cat /root/valid_birds`; do
  echo "<li><a href=/$BIRD>$BIRD</a></li>"
done

echo -n "
<h2> Example </h2>

Try this in your browser or curl:

"
BIRD=`head -n 1 /root/valid_birds`
HOST=`cat /proc/sys/kernel/hostname | tr -d '\n'`
echo "
    <a href=$BIRD>http://$HOST/$BIRD</a>"

echo "
<h2> More info: </h2>

<a href=https://github.com/solarkennedy/equail>Source code</a>
<a href=http://en.wikipedia.org/wiki/Bluetooth_low_energy>Wikipedia on BTLE</a>
"

}

if [ "$url" == "" ]; then
  echo HTTP/1.0 200 OK
  response=`usage`
  echo "Content-Type: text/html; charset=utf-8"
elif ! grep -q -w "$url" /root/valid_birds ; then
  echo HTTP/1.0 404 Not Found
  echo "Content-Type: text/plain; charset=utf-8"
  response="404: I'm not aware of the bird $url."
else 
  response=$(/usr/bin/timeout 15 /usr/sbin/send_beacon "$url" 2>&1)
  ret=$?
  if [ $ret -eq 0 ]; then
    echo HTTP/1.0 200 OK
  else
    echo HTTP/1.0 500
  fi
  echo "Content-Type: text/plain; charset=utf-8"
fi
  
length=$(echo "$response" | wc -c)
echo "Connection: close"
echo "Content-Length: $length"
echo
echo "$response"
