#!/bin/sh
read request
while /bin/true;
do
read header
[ "$header" == $'\r' ] && break;
done

GET="${request#GET }"
HEADER="${GET% HTTP/*}"
url=`echo $HEADER | sed 's/\///'`

usage() {
echo "== Welcome to the Zookeeeper!

The zookeeper is an http api to send Bluetooth Low Energy beacons to compatible
plush toys. 

== Usage

Set your URL to a valid bird. Here is a list of the birds I'm aware of:
"
cat /root/valid_birds

echo -n "
== Example

Try this in your browser or curl:

    http://"


cat /proc/sys/kernel/hostname | tr -d '\n'
echo -n "/"
head -n 1 /root/valid_birds

echo "
== More info:

Source code:

    https://github.com/solarkennedy/equail

Wikipedia:

    http://en.wikipedia.org/wiki/Bluetooth_low_energy
"

}

if [ "$url" == "" ]; then
  echo HTTP/1.0 200 OK
  response=`usage`
elif ! grep -w "$url" /root/valid_birds ; then
  echo HTTP/1.0 404 Not Found
  response="404: I'm not aware of the bird $url."
else 
  response=$(/usr/sbin/send_beacon "$url" 2>&1)
  ret=$?
  if [ $ret -eq 0 ]; then
    echo HTTP/1.0 200 OK
  else
    echo HTTP/1.0 500
  fi
fi
  
length=$(echo "$response" | wc -c)
echo "Content-Type: text/plain; charset=utf-8"
echo "Connection: close"
echo "Content-Length: $length"
echo
echo "$response"
